### ISSUE TITLE
Allow an option to ignore folders

### ISSUE THREAD

**Issue by xshapira** [codescene-oss/codescene-vscode#13]
Whenever I work on a Python project, I get warnings about `pyenv`. It would be great if we could ignore certain folders (especially the ones that start with a dot).

![Screen Shot](https://user-images.githubusercontent.com/48856190/231089548-469b5cb2-2e1e-42ef-a6fa-24a2f6537edd.JPG)

**Comment by sandlunds** [comment]
This is a good suggestion and we will look into it. We could probably add a configurable pattern with ignored files and put in place a reasonable default value.

**Comment by xshapira** [comment]
@sandlunds This is awesome! Thank you for your outstanding work.
