### ISSUE TITLE
Question: Is it possible to scan all files in project?

### ISSUE THREAD

**Issue by Kitton** [codescene-oss/codescene-vscode#24]
Now it scans only the opened files and only after it adds issues to the Problems tab. Is it possible to run the scan on the whole project?

**Comment by sandlunds** [comment]
It's not really something in the road map right now at least, as this is more a task for the full [CodeScene](https://codescene.com) product which has a lot of visualizations for whole projects. As an example:
<img width="1620" alt="image" src="https://github.com/codescene-oss/codescene-vscode/assets/430334/3a4dde75-a24c-41ff-bed8-2b38e0ccf549">
