### ISSUE TITLE
Does the plugin send your code to the cloud by default or when not logged in to CodeScene?

### ISSUE THREAD

**Issue by brokenthorn** [codescene-oss/codescene-vscode#28]
Basically, what I want to ask is: does the plugin send your code to the cloud by default or when not logged in to CodeScene?

This is not clear from the plugin description and while it is advertised as free, nothing is free in life.

Please make this information transparent as this will increase confidence in the product and the company.

Thank you!

**Comment by emilaasa** [comment]
Thanks for creating an issue!

No code is sent to the CodeScene servers from the extension. When logged in, you're able to connect to your own CodeScene Cloud instance, and retrieve more complex analysis data that's mapped to what's in your editor, like Change Coupling.

Here are the two spots we're sending telemetry from:

https://github.com/codescene-oss/codescene-vscode/blob/913e8253848541e7b1ff6ed8b19b4cc57956aa61/src/extension.ts#L70
https://github.com/codescene-oss/codescene-vscode/blob/913e8253848541e7b1ff6ed8b19b4cc57956aa61/src/extension.ts#L150

It gives us basic usage stats.

I'd be happy to hear (and implement!) any suggestions on how to clearly communicate what's being sent in the extension.

**Comment by jlindbergh** [comment]
Closing this with some further clarifications
1. All code analysis is done locally on your computer only.
2. Telemetry is still used pretty extensively to monitor usage, but no private data is sent. Also, telemetry can be user controlled by the **Telemetry Level** vscode setting.
3. When opting in to use the ACE AI services (Auto-Refactor) you're agreeing to the [CodeScene AI Privacy Principles](https://codescene.com/product/ace/principles). Also:
     - Your code is never stored by us or the LLMs
     - Your code snippets are shared only with select LLMs
     - Your code is not used to train any LLM
     - All communications with CodeScene ACE is fully encrypted
