### ISSUE TITLE
CodeScene extension logs into console instead of dedicated output channel

### ISSUE THREAD

**Issue by lmerynda** [codescene-oss/codescene-vscode#32]
Vscode has infrastructure to handle extension specific logging through output channel. Among other benefits It makes organization of logs better, it helps people access data to solve their problems faster with particular extension, and allows for pristine dev console so other issues can be spotted more easily.

Can all the logging be moved to already existing codescene output channel? Extension developers usually create a small util class with basic log(message: string) api.

The issue is specifically annyoing for vscode extension developers such as myself working with extension debugging as the Debug Console will print all of it as seen in the screenshot

![image](https://github.com/codescene-oss/codescene-vscode/assets/7020903/9c68a0d5-cf0b-428f-ab39-1bc98faa10ba)

I'm willing to create a PR for it in my free time, but can't make hard commitments

Otherwise thank you for bringing codescene into vscode ecosystem, I'm a fan :)

**Comment by jlindbergh** [comment]
Hi @Uprzejmy !
Thanks for taking your time reporting this. I agree it's not an optimal logging solution and I can see how this is annoying, especially when developing extensions. We have some stuff in the works at the moment, and we can probably take some time moving over to a proper LogOutputChannel in an upcoming release. It sounds like a simple and reasonable improvement to implement!

And I'm glad to hear you're enjoying CodeScene!

**Comment by jlindbergh** [comment]
Closing this since a dedicated `logOutputChannel` is implemented starting from [v0.7.0](https://github.com/codescene-oss/codescene-vscode/releases/tag/v0.7.0).
**Note:** Default log level in VSCode is `info`. To see more, use the _>Developer: Set Log Level..._ command.
