### ISSUE TITLE
Unable to to match very specific matching_content_path

### ISSUE THREAD

**Issue by m-shojaei** [codescene-oss/codescene-vscode#37]
Hello!
I'm using the snippet below to skip certain checks in my test files but the value for `matching_content_path` seems to be incorrect. But if I changed its value to `**/*.tsx` it would match my test file.

```javascript
{
  "rule_sets": [
    {
      "matching_content_path": "**/*.test.tsx",
      "rules": [
        {
          "name": "Code Duplication",
          "weight": 0.0
        }
      ]
    }
  ]
}
``` 

 Is this an issue or am I doing something wrong?

**Comment by adamtornhill** [comment]
Hi @m-shojaei! Could you share an example on the type of file path you would like to match?

**Comment by m-shojaei** [comment]
Hi @adamtornhill! Here's an example: `./src/components/Header/tests/Header.test.tsx`

**Comment by adamtornhill** [comment]
Thanks for the example. Glob patterns are a bit tricky. In this case, I would use a pattern like `**/tests/**`. That would apply the custom code health rule to all test files without impacting the application code.

**Comment by m-shojaei** [comment]
I understand. We have many tests in our project and didn't want to introduce a hard-to-enforce rule for putting them in a folder called tests.
