### ISSUE TITLE
Extension doesn't do anything

### ISSUE THREAD

**Issue by Sorann753** [codescene-oss/codescene-vscode#41]
## Problem
Hello, i've just installed this extension as i'm very interested in having quality metrics while i'm coding, however i don't see any change in my editor and no metrics nor warning has appeared anywhere in my workspace.

the extension tab does say it is enabled and i haven't changed any settings.
i have tried to restart vscode but nothing new happened.

my issue might be similar to #10 but i still haven't seen it work yet.
could it simply be that the parsing of the files and the calculation of the metrics are taking a long time?

if so, i believe that adding a loading indicator somewhere in the vscode status bar or a notification saying `parsing in progress` could greatly improve the user experience

## Additional info
```
OS : Ubuntu 22
vscode version : 1.85.2
NodeJS version : 18.15.0
CodeScene version : 0.6.1
File Type : C and C++ code
```

**Comment by Sorann753** [comment]
update, after more than a day and multiple restart of vscode i have still not been able to get the extension to work so i don't think it's just taking a long time to load anymore

**Comment by jlindbergh** [comment]
Hi!

Thanks for a detailed report, and sorry to hear about your problems. 
Extension activation should be triggered when opening any supported file, which should indeed happen with your C/C++ files. The review results should be visible as a CodeLens directly in your file or in the Problems view if there are any issues.

I'd suggest looking in the extension settings to make sure that "Enable Code Lenses" isn't accidentally unchecked in your user or workspace settings. It should be checked by default.

Adding some sort of indicator or status view would indeed help. We have something in the works for the next release, but currently the way to see extension info/progress is in the "CodeScene" Output channel (View->Output, select CodeScene in the dropdown). A typical startup messages will look like this:

```
Ensuring we have the latest CodeScene CLI version...
CodeScene CLI is not up to date, downloading latest version
Downloading https://downloads.codescene.io/enterprise/cli/codescene-cli-ide-macos-aarch64-v3.zip <- this might take a while
The latest CodeScene CLI is in place, we are ready to go!
```

Depending on your output I would suggest deleting the `.vscode/extensions/codescene.codescene-vscode-0.6.1/cs-${platform}-${arch}.last-modified` file before restarting again and see what kind of output you get.

I hope this could be of some help.

**Comment by Sorann753** [comment]
Thank you for your answer, i've looked at the config and code lenses is indeed checked, so the issue doesn't come from here
![Screenshot from 2024-02-28 11-00-00](https://github.com/codescene-oss/codescene-vscode/assets/81806598/06c54709-c932-4fac-b68f-8f93f75e947d)

then i have looked at the output for the CodeScene extension and i get the following messages
```
Ensuring we have the latest CodeScene CLI version...
CodeScene CLI already exists and is up to date
```
so i have followed your suggestion and deleted the extension file, here is the messages i had after restarting my vscode
```
Ensuring we have the latest CodeScene CLI version...
CodeScene CLI is not up to date, downloading latest version
Downloading https://downloads.codescene.io/enterprise/cli/codescene-cli-ide-linux-amd64-v3.zip
The latest CodeScene CLI is in place, we are ready to go!
```
after that, no metrics appeared, so i tried restarting my vscode again but i still have nothing.

it is to be noted that i don't restard this computer often, so it might simply be because it need to restart to load some changes? i'll test that later today and update on whether it worked or not

**Comment by Sorann753** [comment]
## update
so after a restart a making sure everything was updated and running, the extension still failed to display any metrics.
i checked in the extension tab and made sure it was actually running and indeed vscode is telling me it is
`Activated by onLanguage:cpp event: 12ms`

so in the process of debuging the issue i've decided to check if the cli which seems to be the back-end of the extension, was actually working, i tried to run `./cs-linux-x64 --help` while being in the extension's folder and got the following message
```
The current machine does not support all of the following CPU features that are required by the image:
[CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.
```
it seems my computer might be a bit too old for the installed tool, for reference here is my neofetch
![Screenshot from 2024-02-28 20-37-55](https://github.com/codescene-oss/codescene-vscode/assets/81806598/a9a3463d-f20f-4b14-ac06-2ad34bf05ce0)

even though it is an old PC i'm still using it quite a lot for coding, is there a version of the CLI i could install to make it work anyway?

**Comment by jlindbergh** [comment]
Good work tracking this down! 
At the very least we should make sure there's some sort of user-facing message for this kind of situation. Also, it should be possible to adjust the compilation target for the binary, making it accessible to a wider range of CPUs. We'll keep this issue open and post any progress here.

Again, thanks for your debugging efforts!

**Comment by emilaasa** [comment]
Elite level debugging @Sorann753 - thanks!

**Comment by jlindbergh** [comment]
Closing this since won't be providing a binary with lesser instruction support in the foreseeable future. It's somewhat more gracefully handled than before though after the fix in https://github.com/codescene-oss/codescene-vscode/pull/45.
