### ISSUE TITLE
Extension error

### ISSUE THREAD

**Issue by Hussein-Ta** [codescene-oss/codescene-vscode#66]
Hi,

I have had used the VS code extension for some time, and have enjoyed it so much!
But it has been some time that the extension is failing to run, and I get this extension error in VS code:

![codescene](https://github.com/codescene-oss/codescene-vscode/assets/68206658/e020c627-35e7-425d-8e96-4b61b918cb68)

I'm running the VS code on a Virtual Machine running Ubuntu 18.02 LTS. 
Is there any way to fix it?

Thanks

**Comment by jlindbergh** [comment]
Hi Hussein and thank you for your report!

I think you are hitting the same issue as in #10 - which means that your VM (or perhaps host) does not support the full instruction set required by the devtools binary.

**Comment by emilaasa** [comment]
@Hussein-Ta It should be resolved now if you update the extension.

**Comment by Hussein-Ta** [comment]
Yes it is working now! Thanks!
