### ISSUE TITLE
Unsupported platform linux-arm64

### ISSUE THREAD

**Issue by sevetseh28** [codescene-oss/codescene-vscode#67]
Hi! Just wanted to report an issue about platform when installing this extension, doesn't seem to support `linux-arm64` <- useful when running devcontainers on  macOS with Silicon chips

**Comment by emilaasa** [comment]
Thanks for reporting - looks like GH recently launched linux arm64 runners beta. We'll look into it!

**Comment by emilaasa** [comment]
https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/

**Comment by Zijie-Tian** [comment]
Same problem.

**Comment by jlindbergh** [comment]
Just published [v0.9.6](https://github.com/codescene-oss/codescene-vscode/releases/tag/v0.9.6) that enables the linux/arm64 support. Enjoy!
