### ISSUE TITLE
Open VSX Publishing

### ISSUE THREAD

**Issue by colin-grant-work** [codescene-oss/codescene-vscode#73]
[Open VSX](https://open-vsx.org/) is an [open-source](https://github.com/eclipse/openvsx) alternative to Microsoft's Visual Studio Marketplace managed by the [Eclipse Foundation](https://projects.eclipse.org/projects/ecd.openvsx) and used by, for example, [VSCodium](https://github.com/VSCodium/vscodium/blob/4aa7ec7928342139113756fb870bbd35db26a282/prepare_vscode.sh#L132). It  would be a great service to the open-source community if this plugin were published to Open VSX as well as the Visual Studio Marketplace.

**Comment by jlindbergh** [comment]
Hi @colin-grant-work and thanks for your comment. Also, sorry for the late response.
We are now [published on open-vsx](https://open-vsx.org/extension/codescene/codescene-vscode) and will keep updating there as well as on VSCode Marketplace going forward.
